name: MLSUHW1
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - python-dateutil
  - pip
  - Py4J
  - pyarrow
  - pyspark
  - seaborn
  - pip:
    - datetime
